- name: Ensure Terraform is Installed
  hosts: all
  become: yes  # Run tasks as sudo
  tasks:

    - name: Clone Git Repository if Not Exists, Else Pull Latest Changes
      ansible.builtin.git:
        repo: "https://github.com/navneet-rathi/ansible-kubernetes-terraform.git"
        dest: "/root/ansible-kubernetes-terraform"
        version: main
        update: yes

    - name: Check if Terraform is Installed
      command: terraform version
      register: terraform_check
      ignore_errors: yes

    - name: Download Terraform
      when: terraform_check.rc != 0
      get_url:
        url: "https://releases.hashicorp.com/terraform/1.11.0/terraform_1.11.0_linux_arm64.zip"
        dest: "/tmp/terraform.zip"

    - name: Unzip Terraform
      when: terraform_check.rc != 0
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Verify Terraform Installation
      command: terraform version
      register: terraform_verify

    - debug:
        msg: "Terraform is successfully installed. Version: {{ terraform_verify.stdout }}"

    - name: Run Terraform Init
      community.general.terraform:
        project_path: "/root/ansible-kubernetes-terraform"
        state: present
        force_init: true

    - name: Apply Terraform Configuration
      community.general.terraform:
        project_path: "/root/ansible-kubernetes-terraform"
        state: present
        force_init: false

    - name: Verify Kubernetes Deployment
      command: kubectl get deployments
      register: k8s_deployments

    - debug:
        msg: "{{ k8s_deployments.stdout }}"